const VOCAB = [
  {chap: '2', greek: 'ἀγάπη', english: 'love', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'ἀλήθεια', english: 'truth', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'δικαιοσύνη', english: 'righteousness', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'εἰρήνη', english: 'peace', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'καρδία', english: 'heart', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'κεφαλή', english: 'head', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'σοφία', english: 'wisdom', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'φωνή', english: 'voice, sound', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'χαρά', english: 'joy', type: 'noun', article: 'ἡ'},
  {chap: '2', greek: 'ψυχή', english: 'soul; life', type: 'noun', article: 'ἡ'},
  {chap: '3', greek: 'ἄνθρωπος', english: 'man; mankind', type: 'noun', article: 'ὁ'},
  {chap: '3', greek: 'δαιμόνιον', english: 'demon', type: 'noun', article: 'τό'},
  {chap: '3', greek: 'δοῦλος', english: 'slave', type: 'noun', article: 'ὁ'},
  {chap: '3', greek: 'εὐαγγέλιον', english: 'good news, gospel', type: 'noun', article: 'τό'},
  {chap: '3', greek: 'θεός', english: 'God', type: 'noun', article: 'ὁ'},
  {chap: '3', greek: 'κύριος', english: 'lord; Lord', type: 'noun', article: 'ὁ'},
  {chap: '3', greek: 'λόγος', english: 'word; reason; account', type: 'noun', article: 'ὁ'},
  {chap: '3', greek: 'παιδίον', english: 'little child; dear child', type: 'noun', article: 'τό'},
  {chap: '3', greek: 'τέκνον', english: 'child', type: 'noun', article: 'τό'},
  {chap: '3', greek: 'υἱός', english: 'son', type: 'noun', article: 'ὁ'},
  {chap: '4', greek: 'ἀκούω', english: 'I hear; I listen', type: 'verb'},
  {chap: '4', greek: 'βάλλω', english: 'I throw; I put', type: 'verb'},
  {chap: '4', greek: 'βλέπω', english: 'I see', type: 'verb'},
  {chap: '4', greek: 'γίνομαι', english: 'I become; it happens (3rd person sing.)', type: 'verb'},
  {chap: '4', greek: 'δέχομαι', english: 'I receive', type: 'verb'},
  {chap: '4', greek: 'ἔρχομαι', english: 'I come, go', type: 'verb'},
  {chap: '4', greek: 'ἐσθίω', english: 'I eat', type: 'verb'},
  {chap: '4', greek: 'ἔχω', english: 'I have, possess; I hold', type: 'verb'},
  {chap: '4', greek: 'λύω', english: 'I loose, loosen, untie; I destroy', type: 'verb'},
  {chap: '4', greek: 'πορεύομαι', english: 'I go, travel', type: 'verb'},
  {chap: '5', greek: 'ἄγω', english: 'I lead, drive', type: 'verb'},
  {chap: '5', greek: 'βαπτίζω', english: 'I baptize', type: 'verb'},
  {chap: '5', greek: 'γράφω', english: 'I write', type: 'verb'},
  {chap: '5', greek: 'διδάσκω', english: 'I teach', type: 'verb'},
  {chap: '5', greek: 'θεραπεύω', english: 'I heal', type: 'verb'},
  {chap: '5', greek: 'λέγω', english: 'I say, speak', type: 'verb'},
  {chap: '5', greek: 'λογίζομαι', english: 'I consider, reckon', type: 'verb'},
  {chap: '5', greek: 'μένω', english: 'I remain', type: 'verb'},
  {chap: '5', greek: 'πιστεύω', english: 'I believe', type: 'verb'},
  {chap: '5', greek: 'σῴζω', english: 'I save; I heal', type: 'verb'},
  {chap: '6', greek: 'ἀγαπάω', english: 'I love', type: 'verb'},
  {chap: '6', greek: 'αἰτέω', english: 'I ask for, request', type: 'verb'},
  {chap: '6', greek: 'γεννάω', english: 'I sire, beget; I give birth to', type: 'verb'},
  {chap: '6', greek: 'ἐρωτάω', english: 'I ask, question', type: 'verb'},
  {chap: '6', greek: 'ζητέω', english: 'I seek; I try to', type: 'verb'},
  {chap: '6', greek: 'καλέω', english: 'I call; I name', type: 'verb'},
  {chap: '6', greek: 'λαλέω', english: 'I talk, speak', type: 'verb'},
  {chap: '6', greek: 'πληρόω', english: 'I fulfill, complete; I fill', type: 'verb'},
  {chap: '6', greek: 'ποιέω', english: 'I do, practice; I make', type: 'verb'},
  {chap: '6', greek: 'φοβέομαι', english: 'I fear, am afraid', type: 'verb'},
  {chap: '6', greek: 'οὐ, οὐκ, οὐχ', english: 'no; not', type: 'negative'},
  {chap: '6', greek: 'οὐχί', english: 'no! (emphatic form of οὐ)', type: 'negative'},
  {chap: '7', greek: 'ἀκολουθέω', english: 'I follow', type: 'verb'},
  {chap: '7', greek: 'ἅπτομαι', english: 'I touch', type: 'verb'},
  {chap: '7', greek: 'ἄρχομαι', english: 'I begin', type: 'verb'},
  {chap: '7', greek: 'διώκω', english: 'I pursue; I persecute', type: 'verb'},
  {chap: '7', greek: 'δοξάζω', english: 'I glorify', type: 'verb'},
  {chap: '7', greek: 'εὐαγγελίζομαι', english: 'I preach the gospel, announce good news', type: 'verb'},
  {chap: '7', greek: 'κηρύσσω', english: 'I announce, proclaim', type: 'verb'},
  {chap: '7', greek: 'κόπτω', english: 'I cut', type: 'verb'},
  {chap: '7', greek: 'πέμπω', english: 'I send', type: 'verb'},
  {chap: '7', greek: 'πράσσω', english: 'I do', type: 'verb'},
  {chap: '8', greek: 'ἀνοίγω', english: 'I open', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'ἀποκαλύπτω', english: 'I reveal, uncover', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'ἀπολύω', english: 'I release, send away; I destroy', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'ἀσπάζομαι', english: 'I greet', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'εἰσέρχομαι', english: 'I go into, enter', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'ἐκβάλλω', english: 'I throw out; I send away; I divorce', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'περιπατέω', english: 'I walk', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'περισσεύω', english: 'I increase; I provide in abundance', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'συνάγω', english: 'I gather together, assemble', type: 'verb', tense: '1st aorist'},
  {chap: '8', greek: 'ὑποτάσσω', english: 'I subject', type: 'verb', tense: '1st aorist'},
  {chap: '9', greek: 'ἁμαρτάνω', english: 'I sin; I err', type: 'verb'},
  {chap: '9', greek: 'ἀναβαίνω', english: 'I go up, ascend', type: 'verb'},
  {chap: '9', greek: 'ἀποθνῄσκω', english: 'I die', type: 'verb'},
  {chap: '9', greek: 'γινώσκω', english: 'I know; I understand, discern', type: 'verb'},
  {chap: '9', greek: 'ἐξέρχομαι', english: 'I go out, depart', type: 'verb'},
  {chap: '9', greek: 'εὑρίσκω', english: 'I find; I obtain', type: 'verb'},
  {chap: '9', greek: 'καταβαίνω', english: 'I go down, descend', type: 'verb'},
  {chap: '9', greek: 'λαμβάνω', english: 'I take, receive', type: 'verb'},
  {chap: '9', greek: 'πίνω', english: 'I drink', type: 'verb'},
  {chap: '9', greek: 'πίπτω', english: 'I fall', type: 'verb'},
  {chap: '9', greek: 'ἥμαρτον', english: 'I sinned; I erred (2nd Aorist of ἁμαρτάνω)', type: 'verb'},
  {chap: '9', greek: 'ἀνέβην', english: 'I went up, ascended (2nd Aorist of ἀναβαίνω)', type: 'verb'},
  {chap: '9', greek: 'ἀπέθανον', english: 'I died (2nd Aorist of ἀποθνῄσκω)', type: 'verb'},
  {chap: '9', greek: 'ἔγνων', english: 'I knew; I understood, discerned (2nd Aorist of γινώσκω)', type: 'verb'},
  {chap: '9', greek: 'ἐξῆλθον', english: 'I went out, departed (2nd Aorist of ἐξέρχομαι)', type: 'verb'},
  {chap: '9', greek: 'εὗρον', english: 'I found; I obtained (2nd Aorist of εὑρίσκω)', type: 'verb'},
  {chap: '9', greek: 'κατέβην', english: 'I went down, descend (2nd Aorist of καταβαίνω)', type: 'verb'},
  {chap: '9', greek: 'ἔλαβον', english: 'I took, received (2nd Aorist of λαμβάνω)', type: 'verb'},
  {chap: '9', greek: 'ἔπιον', english: 'I drank (2nd Aorist of πίνω)', type: 'verb'},
  {chap: '9', greek: 'ἔπεσον', english: 'I fell (2nd Aorist of πίπτω)', type: 'verb'},
  {chap: '9', greek: 'ἤγαγον', english: 'I led, drove (2nd Aorist of ἄγω)', type: 'verb'},
  {chap: '9', greek: 'ἔβαλον', english: 'I threw; I put (2nd Aorist of βάλλω)', type: 'verb'},
  {chap: '9', greek: 'ἐγενόμην', english: 'I became; it happened (3rd person sing.) (2nd Aorist of γίνομαι)', type: 'verb'},
  {chap: '9', greek: 'ἦλθον', english: 'I came, went (2nd Aorist of ἔρχομαι)', type: 'verb'},
  {chap: '9', greek: 'ἔφαγον', english: 'I ate (2nd Aorist of ἐσθίω)', type: 'verb'},
  {chap: '9', greek: 'ἔσχον', english: 'I had, possessed; I held (2nd Aorist of ἔχω)', type: 'verb'},
  {chap: '9', greek: 'εἶπον', english: 'I said, spoke (2nd Aorist of λέγω)', type: 'verb'},
  {chap: '10', greek: 'εἰμί', english: 'I am; I exist', type: 'verb'},
  {chap: '10', greek: 'ἀγαθός, -ή, -όν', english: 'good', type: 'adjective'},
  {chap: '10', greek: 'ἀγαπητός, -ή, -όν', english: 'beloved, dear', type: 'adjective'},
  {chap: '10', greek: 'ἅγιος, -α, -ον', english: 'holy; saints (pl. substantive)', type: 'adjective'},
  {chap: '10', greek: 'δίκαιος, -α, -ον', english: 'righteous, just', type: 'adjective'},
  {chap: '10', greek: 'ἕτερος, -α, -ον', english: 'other, another, different', type: 'adjective'},
  {chap: '10', greek: 'κακός, -ή, -όν', english: 'bad, evil', type: 'adjective'},
  {chap: '10', greek: 'καλός, -ή, -όν', english: 'good, excellent; beautiful, handsome', type: 'adjective'},
  {chap: '10', greek: 'νεκρός, -ά, -όν', english: 'dead', type: 'adjective'},
  {chap: '10', greek: 'πιστός, -ή, -όν', english: 'faithful, believing', type: 'adjective'},
  {chap: '10', greek: 'πονηρός, -ά, -όν', english: 'evil, wicked', type: 'adjective'},
  {chap: '11', greek: 'αἰών, αἰῶνος, ὁ', english: 'age; the world', type: 'noun', article: 'ὁ'},
  {chap: '11', greek: 'αἰώνιος, -ον', english: 'eternal', type: 'adjective'},
  {chap: '11', greek: 'ἀνήρ, ἀνδρός, ὁ', english: 'man; husband', type: 'noun', article: 'ὁ'},
  {chap: '11', greek: 'γυνή, γυναικός, ἡ', english: 'woman; wife', type: 'noun', article: 'ἡ'},
  {chap: '11', greek: 'ὄνομα, ὀνόματος, τό', english: 'name', type: 'noun', article: 'τό'},
  {chap: '11', greek: 'πνεῦμα, πνεύματος, τό', english: 'Spirit; spirit; breath; wind', type: 'noun', article: 'τό'},
  {chap: '11', greek: 'πούς, ποδός, ὁ', english: 'foot', type: 'noun', article: 'ὁ'},
  {chap: '11', greek: 'σάρξ, σαρκός, ἡ', english: 'flesh', type: 'noun', article: 'ἡ'},
  {chap: '11', greek: 'σῶμα, σώματος, τό', english: 'body', type: 'noun', article: 'τό'},
  {chap: '11', greek: 'φῶς, φωτός, τό', english: 'light', type: 'noun', article: 'τό'},
  {chap: '11', greek: 'χείρ, χειρός, ἡ', english: 'hand', type: 'noun', article: 'ἡ'},
  {chap: '12', greek: 'ἀρχιερεύς, -έως, ὁ', english: 'high priest', type: 'noun', article: 'ὁ'},
  {chap: '12', greek: 'βασιλεύς, -έως, ὁ', english: 'king', type: 'noun', article: 'ὁ'},
  {chap: '12', greek: 'γραμματεύς, -έως, ὁ', english: 'scribe', type: 'noun', article: 'ὁ'},
  {chap: '12', greek: 'δύναμις, -εως, ἡ', english: 'power', type: 'noun', article: 'ἡ'},
  {chap: '12', greek: 'ἔθνος, -ους, τό', english: 'nation; Gentiles (pl.)', type: 'noun', article: 'τό'},
  {chap: '12', greek: 'μήτηρ, μητρός, ἡ', english: 'mother', type: 'noun', article: 'ἡ'},
  {chap: '12', greek: 'ὄρος, -ους, τό', english: 'mountain', type: 'noun', article: 'τό'},
  {chap: '12', greek: 'πᾶς, πᾶσα, πᾶν', english: 'all, every; whole', type: 'adjective'},
  {chap: '12', greek: 'πατήρ, πατρός, ὁ', english: 'father', type: 'noun', article: 'ὁ'},
  {chap: '12', greek: 'πίστις, -εως, ἡ', english: 'faith, trust', type: 'noun', article: 'ἡ'},
  {chap: '12', greek: 'πόλις, -εως, ἡ', english: 'city', type: 'noun', article: 'ἡ'},
  {chap: '13', greek: 'ἀπό + gen.', english: 'from (gen)', type: 'preposition'},
  {chap: '13', greek: 'διά + gen.; +acc.', english: 'through (gen); because of (acc)', type: 'preposition'},
  {chap: '13', greek: 'εἰς + acc.', english: 'unto, into, to, in (acc)', type: 'preposition'},
  {chap: '13', greek: 'ἐκ + gen.', english: 'out of, from (gen)', type: 'preposition'},
  {chap: '13', greek: 'ἐν + dat.', english: 'in, on, among, by means of (dat)', type: 'preposition'},
  {chap: '13', greek: 'ἐπί + gen.; + dat.; + acc.', english: 'on, upon (gen); upon, on the basis of (dat); against, upon (acc)', type: 'preposition'},
  {chap: '13', greek: 'κατά + gen.; + acc.', english: 'down from, against (gen); according to (acc)', type: 'preposition'},
  {chap: '13', greek: 'μετά + gen.; + acc.', english: 'with (gen); after (acc)', type: 'preposition'},
  {chap: '13', greek: 'παρά + gen.; + dat.; + acc.', english: 'from, with (gen); with, beside (dat); beside (acc)', type: 'preposition'},
  {chap: '13', greek: 'περί + gen.; + acc.', english: 'concerning, about (gen); around (acc)', type: 'preposition'},
  {chap: '13', greek: 'πρός + acc.', english: 'to, toward, in the presence of (acc)', type: 'preposition'},
  {chap: '13', greek: 'σύν + dat.', english: 'with, along with (dat)', type: 'preposition'},
  {chap: '13', greek: 'ὑπέρ + gen.; + acc.', english: 'on behalf of, for the sake of (gen); above (acc)', type: 'preposition'},
  {chap: '13', greek: 'ὑπό + gen.; + acc.', english: 'by (gen); under (acc)', type: 'preposition'},
  {chap: '14', greek: 'ἀπέρχομαι', english: 'I go away, leave', type: 'verb'},
  {chap: '14', greek: 'ἀπελήλυθα', english: 'I have gone away, have left (Perfect of ἀπέρχομαι)', type: 'verb'},
  {chap: '14', greek: 'ἐγγίζω', english: 'I draw near, approach', type: 'verb'},
  {chap: '14', greek: 'ἤγγικα', english: 'I have drawn near, have approached (Perfect of ἐγγίζω)', type: 'verb'},
  {chap: '14', greek: 'μαρτυρέω', english: 'I testify, bear witness', type: 'verb'},
  {chap: '14', greek: 'μεμαρτύρηκα', english: 'I have testified, have bore witness (Perfect of μαρτυρέω)', type: 'verb'},
  {chap: '14', greek: 'ὁράω', english: 'I see', type: 'verb'},
  {chap: '14', greek: 'ἑώρακα or ἑόρακα', english: 'I have seen (Perfect of ὁράω)', type: 'verb'},
  {chap: '14', greek: 'πείθω', english: 'I persuade', type: 'verb'},
  {chap: '14', greek: 'πέποιθα', english: 'I have persuaded (Perfect of πείθω)', type: 'verb'},
  {chap: '14', greek: 'προσέρχομαι', english: 'I come to, approach', type: 'verb'},
  {chap: '14', greek: 'προσελήλυθα', english: 'I have come to, have approached (Perfect of προσέρχομαι)', type: 'verb'},
  {chap: '14', greek: 'τηρέω', english: 'I keep; I guard', type: 'verb'},
  {chap: '14', greek: 'τετήρηκα', english: 'I have kept; I have guarded (Perfect of τηρέω)', type: 'verb'},
  {chap: '14', greek: 'βασιλεία', english: 'kingdom', type: 'noun', article: 'ἡ'},
  {chap: '14', greek: 'ἔργον', english: 'work; deed', type: 'noun', article: 'τό'},
  {chap: '14', greek: 'καί', english: 'and, also, even', type: 'na'},
  {chap: '15', greek: 'ἐπερωτάω', english: 'I ask; I question', type: 'verb'},
  {chap: '15', greek: 'ζάω', english: 'I live, am alive', type: 'verb'},
  {chap: '15', greek: 'θεωρέω', english: 'I look at, gaze', type: 'verb'},
  {chap: '15', greek: 'παρακαλέω', english: 'I exhort; I comfort, console', type: 'verb'},
  {chap: '15', greek: 'προσεύχομαι', english: 'I pray', type: 'verb'},
  {chap: '15', greek: 'προσκυνέω', english: 'I worship, bow before', type: 'verb'},
  {chap: '15', greek: 'ὑπάγω', english: 'I pass by, depart', type: 'verb'},
  {chap: '15', greek: 'λαός', english: 'people, nation', type: 'noun', article: 'ὁ'},
  {chap: '15', greek: 'ὄχλος', english: 'crowd', type: 'noun', article: 'ὁ'},
  {chap: '15', greek: 'ἤδη', english: 'already', type: 'na'},
  {chap: '16', greek: 'αὐτός, -ή, -ό', english: 'he, she, it; himself, herself, itself; same', type: 'pronoun'},
  {chap: '16', greek: 'ἑαυτοῦ, -ῆς, -οῦ', english: 'himself, herself, itself', type: 'pronoun'},
  {chap: '16', greek: 'ἐγώ', english: 'I', type: 'pronoun'},
  {chap: '16', greek: 'ἐμαυτοῦ', english: 'myself (genitive form; there is no nominative)', type: 'pronoun'},
  {chap: '16', greek: 'ἐμός, -ή, -όν', english: 'my', type: 'pronoun'},
  {chap: '16', greek: 'ἴδιος, -α, -ον', english: 'one’s own; peculiar', type: 'pronoun'},
  {chap: '16', greek: 'οίκία', english: 'household, family; house', type: 'noun', article: 'ἡ'},
  {chap: '16', greek: 'οἶκος', english: 'house; household', type: 'noun', article: 'ὁ'},
  {chap: '16', greek: 'σεαυτοῦ', english: 'yourself (genitive form; there is no nominative)', type: 'pronoun'},
  {chap: '16', greek: 'σύ', english: 'you', type: 'pronoun'},
  {chap: '16', greek: 'ὧδε', english: 'here', type: 'na'},
  {chap: '17', greek: 'δέ', english: 'and; but, however', type: ''},
  {chap: '17', greek: 'εἰ', english: 'if; since; whether', type: ''},
  {chap: '17', greek: 'ἐκεῖνος, ἐκείνη, ἐκεῖνο', english: 'that', type: ''},
  {chap: '17', greek: 'νόμος, ὁ', english: 'law; principle', type: 'noun'},
  {chap: '17', greek: 'ὅτι', english: 'that; because', type: ''},
  {chap: '17', greek: 'οὗτος, αὕτη, τοῦτο', english: 'this; he, she, it', type: 'pronoun'},
  {chap: '17', greek: 'σάββατον, τό', english: 'Sabbath', type: 'noun'},
  {chap: '17', greek: 'τίς, τί', english: 'who? what?; τί can mean why?', type: ''},
  {chap: '17', greek: 'τις, τι', english: 'someone, something; anyone, anything; certain', type: ''},
  {chap: '18', greek: 'αἴρω', english: 'I raise, lift; I carry, remove', type: 'verb'},
  {chap: '18', greek: 'ἀπαγγέλλω', english: 'I announce, report', type: 'verb'},
  {chap: '18', greek: 'ἀποκρίνομαι', english: 'I answer (direct object in dative case)', type: 'verb'},
  {chap: '18', greek: 'ἀποκτείνω', english: 'I kill', type: 'verb'},
  {chap: '18', greek: 'ἀποστέλλω', english: 'I send out', type: 'verb'},
  {chap: '18', greek: 'ἐγείρω', english: 'I raise', type: 'verb'},
  {chap: '18', greek: 'κρίνω', english: 'I judge; I condemn', type: 'verb'},
  {chap: '18', greek: 'σπείρω', english: 'I plant', type: 'verb'},
  {chap: '18', greek: 'ἄγγελος', english: 'angel, messenger', type: 'noun', article: 'ὁ'},
  {chap: '18', greek: 'ἀπόστολος', english: 'apostle; emissary', type: 'noun', article: 'ὁ'},
  {chap: '19', greek: 'ἀρχή', english: 'beginning', type: 'noun', article: 'ἡ'},
  {chap: '19', greek: 'γῆ', english: 'earth; land', type: 'noun', article: 'ἡ'},
  {chap: '19', greek: 'ζωή', english: 'life', type: 'noun', article: 'ἡ'},
  {chap: '19', greek: 'ἡμέρα', english: 'day', type: 'noun', article: 'ἡ'},
  {chap: '19', greek: 'θάνατος', english: 'death', type: 'noun', article: 'ὁ'},
  {chap: '19', greek: 'κόσμος', english: 'world; adornment', type: 'noun', article: 'ὁ'},
  {chap: '19', greek: 'νύξ, νυκτός, ἡ', english: 'night', type: 'noun', article: 'ἡ'},
  {chap: '19', greek: 'οὐρανός', english: 'heaven', type: 'noun', article: 'ὁ'},
  {chap: '19', greek: 'στόμα, στόματος, τό', english: 'mouth', type: 'noun', article: 'τό'},
  {chap: '19', greek: 'κράζω', english: 'I shout, cry out (irregular future and aorist: κράξω, ἔκραξα)', type: 'verb'},
  {chap: '19', greek: 'φέρω', english: 'I bear, carry (irregular future and aorist: οἴσω, ἤνεγκα)', type: 'verb'},
  {chap: '20', greek: 'ὑπάρχω', english: 'I exist; I belong to', type: 'verb'},
  {chap: '20', greek: 'χαίρω', english: 'I rejoice', type: 'verb'},
  {chap: '20', greek: 'ἄρτος', english: 'bread; loaf', type: 'noun', article: 'ὁ'},
  {chap: '20', greek: 'γλῶσσα, -ης, ἡ', english: 'tongue; speech, language', type: 'noun', article: 'ἡ'},
  {chap: '20', greek: 'δόξα, -ης, ἡ', english: 'glory, fame', type: 'noun', article: 'ἡ'},
  {chap: '20', greek: 'θάλασσα, -ης, ἡ', english: 'sea; lake', type: 'noun', article: 'ἡ'},
  {chap: '20', greek: 'καρπός', english: 'fruit', type: 'noun', article: 'ὁ'},
  {chap: '20', greek: 'μή', english: 'no, not (used with non-indicative moods including participles)', type: 'na'},
  {chap: '20', greek: 'ὀφθαλμός', english: 'eye', type: 'noun', article: 'ὁ'},
  {chap: '20', greek: 'πρόσωπον', english: 'face; appearance; person', type: 'noun', article: 'τό'},
  {chap: '20', greek: 'τυφλός, -ή, -όν', english: 'blind (often used as a substantive: ὁ τυφλός “the blind man”)', type: 'adjective'},
  {chap: '21', greek: 'γραφή', english: 'Scripture; writing', type: 'noun', article: 'ἡ'},
  {chap: '21', greek: 'ἐντολή', english: 'commandment', type: 'noun', article: 'ἡ'},
  {chap: '21', greek: 'καιρός', english: 'season; a time, age', type: 'noun', article: 'ὁ'},
  {chap: '21', greek: 'παραβολή', english: 'parable', type: 'noun', article: 'ἡ'},
  {chap: '21', greek: 'ῥῆμα, ῥήματος, τό', english: 'word, speech', type: 'noun', article: 'τό'},
  {chap: '21', greek: 'χρόνος', english: 'time', type: 'noun', article: 'ὁ'},
  {chap: '21', greek: 'ὥρα', english: 'hour', type: 'noun', article: 'ἡ'},
  {chap: '21', greek: 'ἀλλά', english: 'but, however, in contrast', type: 'verb'},
  {chap: '21', greek: 'γάρ', english: 'for, because (postpositive)', type: 'verb'},
  {chap: '21', greek: 'εὐθύς', english: 'immediately', type: 'verb'},
  {chap: '21', greek: 'οὖν', english: 'therefore, then (continuation of an argument) (postpositive)', type: 'verb'},
  {chap: '22', greek: 'ἀμήν', english: 'truly', type: 'adverb'},
  {chap: '22', greek: 'ἄν (not usually translated; indefinite particle)', english: 'ever', type: 'adverb'},
  {chap: '22', greek: 'ἐάν', english: 'if, if ever (combination of εἰ and ἄν)', type: 'na'},
  {chap: '22', greek: 'ἐὰνμή', english: 'unless; if not', type: 'na'},
  {chap: '22', greek: 'ἕως', english: 'until; while (adverb); as prep. + gen. to, until', type: 'na'},
  {chap: '22', greek: 'ἵνα', english: 'in order that; that', type: 'na'},
  {chap: '22', greek: 'ὅπου', english: 'where (ὅπου ἄν or ὅπου ἐάν, wherever, whenever)', type: 'na'},
  {chap: '22', greek: 'ὅπως', english: 'in order that; that', type: 'na'},
  {chap: '22', greek: 'ὅταν', english: 'when, whenever', type: 'na'},
  {chap: '22', greek: 'ὅτε', english: 'when', type: 'na'},
  {chap: '22', greek: 'οὕτως', english: 'so, thus, in this way', type: 'na'},
  {chap: '22', greek: 'ὡς', english: 'as; like (with numbers: “about” “approximately”)', type: 'na'},
  {chap: '23', greek: 'οἶδα', english: 'I know', type: 'verb'},
  {chap: '23', greek: 'ἀδελφός', english: 'brother', type: 'noun'},
  {chap: '23', greek: 'ἀλλήλων', english: '(of) one another (reciprocal pronoun; the genitive plural is the lexical form)', type: 'verb'},
  {chap: '23', greek: 'ἄλλος, -η, -ο', english: 'other, another', type: 'na'},
  {chap: '23', greek: 'ἐξουσία', english: 'authority; power', type: 'noun', article: 'ἡ'},
  {chap: '23', greek: 'ἰδού', english: 'look! behold! (an old imperative form from εἶδον that has become a particle)', type: 'verb'},
  {chap: '23', greek: 'λίθος', english: 'stone', type: 'noun'},
  {chap: '23', greek: 'λοιπός', english: 'remaining, rest', type: 'na'},
  {chap: '23', greek: 'ὅς, ἥ, ὅ', english: 'who, which', type: 'na'},
  {chap: '23', greek: 'ὅσος, -η, -ον', english: 'as much as, as many as; as great as; all that', type: 'adjective'},
  {chap: '23', greek: 'τοιοῦτος, τοιαύτη, τοιοῦτο(ν)', english: 'of such a kind, such as this, such', type: 'na'},
  {chap: '24', greek: 'διδάσκαλος', english: 'teacher', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'ἔρημος, -ον', english: 'deserted (adjective; masculine and feminine shares one form)', type: 'adjective'},
  {chap: '24', greek: 'ἔρημος, ἡ', english: 'desert, wilderness', type: 'noun', article: 'ἡ'},
  {chap: '24', greek: 'θρόνος', english: 'throne', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'Ἰησοῦς', english: 'Jesus', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'Ἰωάννης', english: 'John', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'μαθητής', english: 'disciple', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'ὁδός', english: 'road, way', type: 'noun', article: 'ἡ'},
  {chap: '24', greek: 'προφήτης', english: 'prophet', type: 'noun', article: 'ὁ'},
  {chap: '24', greek: 'σημεῖον', english: 'sign; miracle', type: 'noun', article: 'τό'},
  {chap: '24', greek: 'συναγωγή', english: 'synagogue', type: 'noun', article: 'ἡ'},
  {chap: '24', greek: 'Χριστός', english: 'Christ, Messiah; anointed one', type: 'noun', article: 'ὁ'},
  {chap: '25', greek: 'ἕκαστος, -η, -ον', english: 'each', type: 'adjective'},
  {chap: '25', greek: 'ἐνώπιον', english: 'in the presence of, before (prep. + genitive)', type: 'na'},
  {chap: '25', greek: 'ἐπαγγελία', english: 'promise', type: 'noun', article: 'ἡ'},
  {chap: '25', greek: 'ἤ', english: 'or; than', type: 'na'},
  {chap: '25', greek: 'κἀγώ', english: 'and I; even I', type: 'na'},
  {chap: '25', greek: 'μέν', english: 'and', type: 'na'},
  {chap: '25', greek: 'μηδέ', english: 'nor, and not (with non-indicative moods)', type: 'na'},
  {chap: '25', greek: 'οὐδέ', english: 'nor, and not', type: 'na'},
  {chap: '25', greek: 'πῶς', english: 'how; how?', type: 'na'},
  {chap: '25', greek: 'ὕδωρ, ὕδατος, τό', english: 'water', type: 'noun', article: 'τό'},
  {chap: '25', greek: 'χάρις, χάριτος, ἡ', english: 'grace, favor', type: 'noun', article: 'ἡ'},
  {chap: '26', greek: 'δεῖ', english: 'it is necessary, one must', type: 'na'},
  {chap: '26', greek: 'δοκέω', english: 'I seem to; I suppose, think', type: 'verb'},
  {chap: '26', greek: 'δύναμαι', english: 'I am able to, I can', type: 'verb'},
  {chap: '26', greek: 'θέλω', english: 'I want to, wish', type: 'verb'},
  {chap: '26', greek: 'μέλλω', english: 'I am about to; it is destined (in third person)', type: 'verb'},
  {chap: '26', greek: 'ἁμαρτία', english: 'sin', type: 'noun', article: 'ἡ'},
  {chap: '26', greek: 'θέλημα, θελήματος, τό', english: 'will, wish', type: 'noun', article: 'τό'},
  {chap: '26', greek: 'ἱμάτιον', english: 'clothing; coat', type: 'noun', article: 'τό'},
  {chap: '26', greek: 'πλοῖον', english: 'boat', type: 'noun', article: 'τό'},
  {chap: '26', greek: 'πρό + gen.', english: 'before, beforehand; in front of', type: 'verb'},
  {chap: '26', greek: 'ὥστε', english: 'so that, with the result that; so as', type: 'verb'},
  {chap: '27', greek: 'ἀνίστημι', english: 'I stand up, arise', type: 'verb'},
  {chap: '27', greek: 'δίδωμι', english: 'I give', type: 'verb'},
  {chap: '27', greek: 'ἵστημι', english: 'I stand', type: 'verb'},
  {chap: '27', greek: 'ἔστησα', english: 'I stood [something] up (1st Aorist of ἵστημι. transitive)', type: 'verb'},
  {chap: '27', greek: 'ἔστην', english: 'I stood up (2nd aorist of ἵστημι. intransitive)', type: 'verb'},
  {chap: '27', greek: 'παραδίδωμι', english: 'I hand over, betray', type: 'verb'},
  {chap: '27', greek: 'τίθημι', english: 'I place, put; appoint', type: 'verb'},
  {chap: '27', greek: 'αἷμα, αἷματος, τό', english: 'blood', type: 'noun', article: 'τό'},
  {chap: '27', greek: 'ἱερόν', english: 'temple', type: 'noun', article: 'τό'},
  {chap: '27', greek: 'πύρ, πυρός, τό', english: 'fire', type: 'noun', article: 'τό'},
  {chap: '27', greek: 'τόπος', english: 'place', type: 'noun', article: 'ὁ'},
  {chap: '27', greek: 'τότε', english: 'then, at that time', type: 'verb'},
  {chap: '28', greek: 'ἀπόλλυμι/ἀπολλύω', english: 'I destroy (middle: I perish)', type: 'verb'},
  {chap: '28', greek: 'ἀφίημι', english: 'I forgive; I allow; I dismiss', type: 'verb'},
  {chap: '28', greek: 'κάθημαι', english: 'I sit; I stay', type: 'verb'},
  {chap: '28', greek: 'φημί', english: 'I say', type: 'verb'},
  {chap: '28', greek: 'δεξιός, -ά, -όν', english: 'right', type: 'adjective'},
  {chap: '28', greek: 'διό', english: 'wherefore, therefore', type: 'verb'},
  {chap: '28', greek: 'εἴτε', english: 'if, whether', type: 'verb'},
  {chap: '28', greek: 'καθώς', english: 'just as, as', type: 'verb'},
  {chap: '28', greek: 'μέσος, -η, -ον', english: 'middle', type: 'adjective'},
  {chap: '28', greek: 'νῦν', english: 'now, at present', type: 'na'},
  {chap: '28', greek: 'οὔτε', english: 'not, nor', type: 'na'},
  {chap: '28', greek: 'τέ', english: 'and, but, also (postpositive)', type: 'na'},
  {chap: '29', greek: 'ἀληθής, -ές', english: 'true; genuine', type: 'na'},
  {chap: '29', greek: 'ἐκεῖ', english: 'there, in that place (adv.)', type: 'na'},
  {chap: '29', greek: 'ἔξω', english: 'out(side) (adv.); + gen., out of', type: 'na'},
  {chap: '29', greek: 'ἔτι', english: 'still, yet (adv.)', type: 'na'},
  {chap: '29', greek: 'μακάριος, -α, -ον', english: 'blessed', type: 'adjective'},
  {chap: '29', greek: 'μᾶλλον', english: 'more; rather', type: 'na'},
  {chap: '29', greek: 'μέγας, μεγάλη, μέγα', english: 'great; large', type: 'na'},
  {chap: '29', greek: 'μείζων, μεῖζον', english: 'greater; larger (comparative of μέγας)', type: 'na'},
  {chap: '29', greek: 'πάλιν', english: 'again (adv.)', type: 'na'},
  {chap: '29', greek: 'πλείων, πλεῖον', english: 'more; greater (comparative of πολύς)', type: 'na'},
  {chap: '29', greek: 'πολύς, πολλή, πολύ', english: 'much, many; often (adv.)', type: 'na'},
  {chap: '29', greek: 'πρεσβύτερος, -α, -ον', english: 'older, elder (comparative of πρεσβύς)', type: 'adjective'},
  {chap: '30', greek: 'δύο', english: 'two (not declined)', type: 'na'},
  {chap: '30', greek: 'δώδεκα', english: 'twelve (not declined)', type: 'na'},
  {chap: '30', greek: 'εἷς, μία, ἕν', english: 'one', type: 'na'},
  {chap: '30', greek: 'ἐλπίς, ἐλπίδος, ἡ', english: 'hope', type: 'noun', article: 'ἡ'},
  {chap: '30', greek: 'ἑπτά', english: 'seven (not declined)', type: 'na'},
  {chap: '30', greek: 'ἔσχατος, -η, -ον', english: 'last, final', type: 'adjective'},
  {chap: '30', greek: 'μηδείς, μηδεμία, μηδέν', english: 'no one', type: 'na'},
  {chap: '30', greek: 'μόνος, -η, -ον', english: 'only, the single', type: 'adjective'},
  {chap: '30', greek: 'ὅλος, -η, -ον', english: 'whole, entire', type: 'adjective'},
  {chap: '30', greek: 'οὐδείς, οὐδεμία, οὐδέν', english: 'no one', type: 'na'},
  {chap: '30', greek: 'πρῶτον', english: 'first, in the first place; earlier', type: 'na'},
  {chap: '30', greek: 'πρῶτος, -η, -ον', english: 'first', type: 'adjective'},
  {chap: '30', greek: 'τρεῖς', english: 'three', type: 'na'},
];

let currentGame;

function Game(vocab) {
  this.index = 0;
  this.vocab = vocab;

  this.nextWord = () => { this.index += 1; };
  this.isMoreWords = () => { return this.index < this.vocab.length - 1 };
}

const randomizeList = (list) => {
  for (let i = list.length - 1; i > 0; i--) {
    let j = Math.floor(Math.random() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
};

const parseSelection = (selectedOptions) => {
  const selections = [];
  Array.from(selectedOptions).forEach((currentOption) => {
    selections.push(currentOption.value);
  });
  return selections;
};

const initializeGame = (vocab) => {
  randomizeList(vocab);
  currentGame = new Game(vocab);
};

const nextWord = () => {
  currentGame.nextWord()
};

const setupCard = (question, answer) => {
  question.textContent = currentGame.vocab[currentGame.index].greek;
  answer.style.display = 'none';
  question.style.display = 'inline';
  answer.textContent = currentGame.vocab[currentGame.index].english;
};

window.onload = () => {
  const question = document.querySelector('#card .question');
  const answer = document.querySelector('#card .answer');

  const revealBttn = document.getElementById('reveal');
  revealBttn.onclick = () => {
    if (question.style.display == 'none') {
      question.style.display = 'inline';
      answer.style.display = 'none';
    } else {
      question.style.display = 'none';
      answer.style.display = 'inline';
    }
  };

  const nextBttn = document.getElementById('next');
  nextBttn.onclick = (event) => {
    nextWord();
    setupCard(question, answer);
    nextBttn.disabled = !currentGame.isMoreWords();
  };

  const startBttn = document.getElementById('start');
  startBttn.onclick = (event) => {
    const selector = document.getElementById('chapterSelect');
    const vocabSelection = parseSelection(selector.selectedOptions);
    const availableVocab = vocabSelection.includes('0') ? VOCAB : VOCAB.filter((word) => vocabSelection.includes(word.chap));

    if (!availableVocab || typeof availableVocab === 'undefined' || availableVocab.length == 0) {
      return;
    }

    initializeGame(availableVocab);
    revealBttn.disabled = false;
    nextBttn.disabled = false;
    setupCard(question, answer);
  };

};
